name: Azure ML Workflow
on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev] #[dev, test, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: python3 .github/utils/installDependencies.py
      
      - name: Set Env Variables
        run: python3 .github/utils/setEnvVariables.py variables/${{ matrix.environment }}/parameters/parameters.json

      - name: Azure login
        run: |
          echo ${{ secrets.ARM_CLIENT_ID }}
          az login --service-principal \
          --username "${{ secrets.ARM_CLIENT_ID }}" \
          --password "${{ secrets.ARM_CLIENT_SECRET }}" \
          --tenant "${{ secrets.ARM_TENANT_ID }}"
      
      - name: Compile Bicep templates
        run: |
          bicep build ./core/infra/main.bicep
    
      - name: Deploy Bicep templates
        run: |
          python3 .github/utils/createAzureResources.py variables/${{ matrix.environment }}/parameters/parameters.json
          


# RBAC Assignments: Nice to have, not essential, to implement we would need to set up security groups or managed identity and assign roles to them. 

# Maybe Skip?
# Generate Python Wheel Files 
# PAT Token 
# Git Config
# Create Repos    
# Secret Scopes        
# Repo Pull  

# ToDo
# Create Cluster  - Done 
# Create mltable - Done 
# Create data asseets  - Done 
# Create environments - Done 
# Create pipeline - Started (50%, needs debugging)
# Create components - Started (50%, needs debugging)
# Model deployment - Not Started
# Monitoring - Not Started


