name: Azure ML Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev] #[dev, test, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt-get update
          pip3 install --upgrade pip
          # pip3 install yq
          # pip3 install azure-cli --upgrade
          # az extension add -n azure-cli-ml
          # az extension add -n azureml-ai-ml
          
          
          # pip3 install azure-cli-ml --upgrade
          # pip3 install azure-ai-ml
          # pip3 install mltable
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages/any/
          sudo apt-get update
          sudo apt-get install gh

          

