name: Azure ML Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev] #[dev, test, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python3 .github/utils/installDependencies.py
      - name: Set Env Variables 
        run: python3 .github/utils/createEnvVariables.py
        env:
          file: variables/${{ matrix.environment }}/parameters
           
      
        # - name: Create or update Azure service principal
      #   env:
      #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #   run: |
      #     python my_script.py
      #   shell: bash
      


          

